#!/bin/sh

sudo dnf update -y

### Temporary
wget https://kojipkgs.fedoraproject.org//packages/labwc/0.9.0/1.fc42/x86_64/labwc-0.9.0-1.fc42.x86_64.rpm
sudo dnf install ./labwc-0.9.0-1.fc42.x86_64.rpm -y
rm labwc-0.9.0-1.fc42.x86_64.rpm

sudo dnf install Xwayland foot swaybg -y
mkdir -p ~/.config/labwc ~/.config/systemd/user

cat > ~/.config/autostart << EOF
swaybg -c "#21333b"
EOF

cat > ~/.config/systemd/user/labwc.service << EOF
[Unit]
Description=labwc

[Service]
Type=simple
ExecStart=labwc

[Install]
WantedBy=default.target
EOF

systemctl --user enable --now labwc.service
