#!/bin/sh

### Temporary
wget https://kojipkgs.fedoraproject.org//packages/labwc/0.9.0/1.fc42/x86_64/labwc-0.9.0-1.fc42.x86_64.rpm
sudo dnf install ./labwc-0.9.0-1.fc42.x86_64.rpm -y
rm labwc-0.9.0-1.fc42.x86_64.rpm

sudo dnf install Xwayland foot swaybg wlr-randr sfwbar -y
mkdir -p ~/.config/labwc ~/.config/systemd/user

cat > ~/.config/labwc/autostart << EOF
swaybg -c "#21333b" &

wlrFirstMonitor=\$(wlr-randr --json | jq -r '[.[]][0].name')
wlr-randr --output \$wlrFirstMonitor --mode 1920x1080

sfwbar &
EOF

cat > ~/.config/systemd/user/labwc.service << EOF
[Unit]
Description=labwc

[Service]
Type=simple
ExecStart=labwc

[Install]
WantedBy=default.target
EOF

cp /usr/share/applications/footclient.desktop ~/.local/share/applications
cp /usr/share/applications/foot-server.desktop ~/.local/share/applications
echo "NoDisplay=true" >> ~/.local/share/applications/footclient.desktop
echo "NoDisplay=true" >> ~/.local/share/applications/foot-server.desktop

systemctl --user enable --now labwc.service
